# 競馬予想システム設定ファイル

# システム全般設定
system:
  version: "3.0"
  debug_mode: false
  log_level: "INFO"
  cache_enabled: true
  max_threads: 4

# 予想エンジン設定
predictor:
  # データドリブン最適化重み
  weights:
    distance_fit: 0.35      # 距離適性（最重要）
    track_condition: 0.20   # 馬場適性
    jockey: 0.15           # 騎手
    running_style: 0.12    # 脚質適性
    bloodline: 0.08        # 血統適性
    recent_form: 0.06      # 近走成績
    course_fit: 0.04       # コース適性
  
  # 戦略ゾーン設定
  strategy_zones:
    premium:
      min_odds: 10.0
      max_odds: 19.9
      priority: "high"
      recommendation: "積極推奨"
    
    good:
      ranges:
        - [1.0, 1.4]
        - [7.0, 9.9]
      priority: "medium"
      recommendation: "安定投資"
    
    caution:
      min_odds: 1.5
      max_odds: 2.9
      priority: "low"
      recommendation: "慎重評価"
    
    avoid:
      min_odds: 50.0
      max_odds: 999.9
      priority: "none"
      recommendation: "回避推奨"

# 合成オッズ計算設定
synthetic_odds:
  min_odds_threshold: 4.0   # 最低合成オッズ
  min_bet_amount: 100       # 最低購入金額
  max_combinations: 5       # 最大組み合わせ数
  default_budget: 1000      # デフォルト予算

# データベース設定
database:
  odds_database_enabled: true
  historical_years: 15
  estimated_races: 48600
  update_frequency: "daily"

# 騎手評価設定
jockeys:
  tier1: ["C.ルメール", "武豊", "戸崎圭太"]
  tier2: ["川田将雅", "M.デムーロ", "福永祐一", "池添謙一", "横山武史"]
  tier3: ["松岡正海", "藤岡佑介", "岩田康誠", "鮫島克駿"]
  
  scores:
    tier1: 90.0
    tier2: 85.0
    tier3: 75.0
    default: 55.0

# 距離カテゴリ設定
distance_categories:
  芝:
    sprint: [1000, 1399]
    mile: [1400, 1899]
    intermediate: [1900, 2199]
    long: [2200, 2799]
    extended: [2800, 3600]
  
  ダート:
    sprint: [1000, 1399]
    mile: [1400, 1899]
    intermediate: [1900, 2199]
    long: [2200, 2799]
    extended: [2800, 3600]

# 出力設定
output:
  format: "structured"
  show_breakdown: true
  show_strategy_zones: true
  show_betting_recommendations: true
  max_recommendations: 5
  decimal_places: 3

# Web検索設定（オプション）
web_search:
  enabled: false
  timeout: 10
  max_retries: 3
  cache_duration: 3600  # 1時間

# PDF処理設定
pdf_processing:
  enabled: true
  max_file_size: "50MB"
  supported_formats: ["pdf"]
  extraction_method: "pdfplumber"

# エラーハンドリング設定
error_handling:
  fallback_mode: true
  show_confidence: true
  min_confidence_threshold: 0.7
  error_log_enabled: true

# キャッシュ設定
cache:
  enabled: true
  ttl: 86400  # 24時間
  max_size: "100MB"
  cleanup_interval: 3600  # 1時間
